### ISSUE TITLE
'dot': undefined method 'dot' for Cumo::NArray:Class (NoMethodError)

### ISSUE THREAD

**Issue by dpblnt** [unagiootoro/ruby-dnn#21]
```
xor.rb:23:in `dot': undefined method `dot' for Cumo::NArray:Class (NoMethodError)
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/functions/basic.rb:142:in `forward'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/functions.rb:10:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/functions/basic.rb:137:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/functions.rb:5:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/base_tensor.rb:93:in `dot'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/layers/basic_layers.rb:243:in `forward'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/layers/basic_layers.rb:28:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/models.rb:508:in `block in forward'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/models.rb:507:in `each'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/models.rb:507:in `forward'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/models.rb:155:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:160:in `on_train_step_default'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:379:in `on_train_step'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:239:in `train_step'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:187:in `update_trainer_impl'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:362:in `update'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ruby-dnn-2.0.0/lib/dnn/core/trainer.rb:29:in `fit'
        from xor.rb:58:in `<main>'
```

So finally I was able to build cumo (0.4.3)
But now I can not use it in ruby-dnn.
I added the following lines to the xor example:
```
require "cumo"
  SFloat = Cumo::SFloat
  class SFloat
    alias mean_original mean
    def mean(*args)
      if size == 1
        self[0]
      else
        mean_original(*args)
      end
    end
  end
```
I'd appreciate any help at this point.

**Comment by dpblnt** [comment]
```require "cumo/narray"``` is the solution
